#!/bin/bash
# Copyright © 2017, Lukas Werling
# 
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# 
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# Script that shows a live plot of effective processor frequency. Use in
# conjunction with amdpstate.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
data=$(mktemp -t amdpstate-frequency.XXXX)
echo $data
maxcpu=$(awk '/^processor/{print $3}' /proc/cpuinfo | tail -n1)

sudo true # Make sure sudo is unlocked before starting gnuplot.

sleep 2 && \
	gnuplot -e "data='\"$data\"'" \
	        -e "maxcpu='$maxcpu'" \
	        "$DIR/frequency.gpi" &

while true; do
	sudo "$DIR/../build/tools/amdpstate" -call frequency 1000 >> "$data"
done
